version: "3"
services:
  akka-serverless-proxy-land:
    image: gcr.io/akkaserverless-public/akkaserverless-proxy:0.7.0-beta.9
    command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.eventing.support=google-pubsub-emulator
    ports:
      - "9000:9000"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8080}
      PUBSUB_EMULATOR_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
  akka-serverless-proxy-item:
    image: gcr.io/akkaserverless-public/akkaserverless-proxy:0.7.0-beta.9
    command: -Dconfig.resource=dev-mode.conf -Dakkaserverless.proxy.eventing.support=google-pubsub-emulator -Dakkaserverless.proxy.http-port=9010 -Dakkaserverless.proxy.user-function-port=8090
    ports:
      - "9010:9010"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8090}
      PUBSUB_EMULATOR_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}    
  gcloud-pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:341.0.0
    command: gcloud beta emulators pubsub start --project=test --host-port=0.0.0.0:8085
    ports:
      - 8085:8085
